name: lokvoice
description: "A new Flutter project."
publish_to: 'none' # This is a private project, not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.8.4
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  video_player: ^2.7.0
  url_launcher: ^6.2.6
  flutter_emoji: ^2.0.0
  google_fonts: ^6.1.0
  readmore: ^2.2.0

  # Media
  image_picker: ^1.0.7
  http: ^1.4.0
  path: ^1.8.3
  mime: ^1.0.4
  intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/arjun_mehta.png
    - assets/images/jan_vikas_logo.png
    - assets/avatar_placeholder.png
    - assets/congress_logo.png
    - assets/rahul.png
    - assets/bjp_logo.png
    - assets/modi.png
    - assets/images/lokvoice_banner.png
    
